version: '3'

services:
  reverse:
    container_name: openurfu-proxy
    hostname: openurfu-proxy
    restart: always
    image: nginx:alpine
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - ./nginx:/etc/nginx
      - ./ssl:/etc/ssl/private
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - mailcow
networks:
  mailcow:
    external:
      name: br-mailcow